version: '3'
services:
my-app:
image: 423623856295.dkr.ecr.eu-central-1.amazonaws.com/my-app:latest
ports: 
- 3000:3000
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=123

  mongo-express:
    image: mongo-express
    ports:
      - "5000:8081"
    restart: always
    depends_on:
      - mongodb
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongodb
